spring:
  datasource:
    url: jdbc:postgresql://db:5432/todoapp
    username: todoapp
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
